framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: 'doctrine://default'
                options:
                    queue_name: default
                    redeliver_timeout: 3600
                    auto_setup: false
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed&auto_setup=false'
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []
        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async